.TH vh_multihub "1" "June 2011" verlihub-1.0 "June 2011"
.SH NAME
vh_multihub \- This is a utility to run, restart and stop hubs with VerliHub
.SH OPTIONS
.TP
.BR -l, --list
The option shows you a list of added hubs and their status. First number show the identifier (ID) of the entry. Green color means that hub is running, red color that hub is stopped.
.TP
.BR -a, --add
The option allows you to add a new hub to config file following the instructions. Remember that you 
.I cannot add
more hubs with same config path.
.TP
.BR "-d, --del [ID]"
This option allows you to delete an entry. You can specify the entry ID to delete as parameter or run the script without any option. In the later case the script proposes you a list of the hubs and it asks to choose the entry you want to delete.
.TP
.BR "-r, --run [ID]"
These options allow you to start hubs. You can specify an entry ID as parameter or run the script option only. In the later case the script proposes you a list of the hubs and it asks to choose the entry you want to manager. You can also use the character A to select all hubs.
.TP
.BR "-s, --stop [ID]"
These options allow you to stop hubs. For more information see run option.
.TP
.BR "-q, --restart [ID]" 
These options allow you to restart hubs. For more information see run option.
.TP
.BR "-v, --version"
This option prints version information about this script and VerliHub.
.TP
.BR -h, --help
displays this help message
.SH "SPECIFIC FILE DESCRIPTIONS"
All hubs are stored inside a config file called verlihub.conf and it is located in /etc/ folder. This file is structured like /etc/passwd file. Each line represents an hub entry and one line contains the following values separeted by a ":"
.TP
.BR "CONFIG_PATH:NICKNAME:PROCESS_OWNER:DATE"
.P
where
.TP
.BR CONFIG_PATH
is the complete path to dbconfig file of the hub
.TP
.BR NICKNAME
is just a reference to the hub (for i.e. the hub owner)
.TP
.BR PROCESS_OWNER
is the username that should run the process (you can use this value if you want to allow server access with different users)
.TP
.BR DATE
the unix timestamp of the last changes
.P
Please do not edit this file but use the options of vh_multihub script.
.SH AUTHOR
Stefano <stefano@verlihub-project.org>
.SH REPORTING BUGS
Report bugs to <http://www.verlihub-project.org>
.br
Support forums: <http://www.verlihub-project.org/discussions>
.br
Wiki pages: <http://www.verlihub-project.org/page>
.br
Translate VerliHub using Transifex.net on <https://www.transifex.net/projects/p/verlihub/>
.SH COPYRIGHT
Copyright \(co 2011 Free Software Foundation, Inc.
License GPLv2: GNU GPL version 2 <http://gnu.org/licenses/gpl.html>.
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.