#!/bin/bash

echo "insert igonre into reglist (nick,login_pwd,class,pwd_crypt,pwd_change,reg_date) values " > odchreglist.sql
cat reglist|sed -e "s/\(['\\\"]\)/\\\\\1/g" |sed  -e "s/^\(\S*\) \(.*\) \(.\)\$/('\1','\2',1+\3,1,0,unix_timestamp(now())),/" >> odchreglist.sql

