# - Find PCRE
# Find the PCRE includes and client library
# This module defines
#  PCRE_INCLUDE_DIR, where to find mysql.h
#  PCRE_LIBRARIES, the libraries needed to use GeoIP.
#  PCRE_FOUND, If false, do not try to use GeoIP.
#
	
IF(PCRE_INCLUDE_DIR AND PCRE_LIBRARIES)
	SET(PCRE_FOUND TRUE)
ELSE(PCRE_INCLUDE_DIR AND PCRE_LIBRARIES)
	FIND_PROGRAM(PCRE_CONFIG_EXECUTABLE pcre-config PATHS /usr/bin $ENV{PCRE_DIR}/bin)
	EXEC_PROGRAM(${PCRE_CONFIG_EXECUTABLE} ARGS "--version" OUTPUT_VARIABLE PCRE_VERSION)
	IF(PCRE_CONFIG_EXECUTABLE)
		MESSAGE(STATUS "Found libpcre ${PCRE_VERSION}")
	ENDIF(PCRE_CONFIG_EXECUTABLE)
	
	FIND_PATH(PCRE_INCLUDE_DIR pcre.h /usr/include /usr/local/include)
	FIND_LIBRARY(PCRE_LIBRARIES NAMES pcre PATHS /usr/lib /usr/local/lib)

	IF(PCRE_INCLUDE_DIR AND PCRE_LIBRARIES)
		SET(PCRE_FOUND TRUE)
		MESSAGE(STATUS "Found libpcre: ${PCRE_INCLUDE_DIR}, ${PCRE_LIBRARIES}")
	ELSE(PCRE_INCLUDE_DIR AND PCRE_LIBRARIES)
		SET(PCRE_FOUND FALSE)
		MESSAGE(STATUS "libpcre not found.")
	ENDIF(PCRE_INCLUDE_DIR AND PCRE_LIBRARIES)
	
	
	mark_as_advanced(PCRE_INCLUDE_DIR PCRE_LIBRARIES)
ENDIF(PCRE_INCLUDE_DIR AND PCRE_LIBRARIES)
