# - Find VerliHub
# Find the VerliHub includes and library
# This module defines
#  VERLIHUB_INCLUDE_DIR, where to find mysql.h
#  VERLIHUB_LIBRARIES, the libraries needed to use GeoIP.
#  VERLIHUB_FOUND, If false, do not try to use GeoIP.
#
	
IF(VERLIHUB_INCLUDE_DIR AND VERLIHUB_LIBRARIES)
	SET(VERLIHUB_FOUND TRUE)
ELSE(VERLIHUB_INCLUDE_DIR AND VERLIHUB_LIBRARIES)
	find_path(VERLIHUB_INCLUDE_DIR cserver.h
		PATHS /usr/include /usr/local/include
		PATH_SUFFIXES verlihub
	)
	find_library(VERLIHUB_LIBRARIES NAMES verlihub vhapi PATHS
		/usr/lib
		/usr/local/lib
	)
	IF(VERLIHUB_INCLUDE_DIR AND VERLIHUB_LIBRARIES)
		SET(VERLIHUB_FOUND TRUE)
		MESSAGE(STATUS "Found VerliHub: ${VERLIHUB_INCLUDE_DIR}, ${VERLIHUB_LIBRARIES}")
	ELSE(VERLIHUB_INCLUDE_DIR AND VERLIHUB_LIBRARIES)
		SET(VERLIHUB_FOUND FALSE)
		MESSAGE(STATUS "VerliHub not found. Please install VerliHub.")
	ENDIF(VERLIHUB_INCLUDE_DIR AND VERLIHUB_LIBRARIES)
	
	mark_as_advanced(VERLIHUB_INCLUDE_DIR VERLIHUB_LIBRARIES)
ENDIF(VERLIHUB_INCLUDE_DIR AND VERLIHUB_LIBRARIES)