#!/bin/bash

prefix=/usr/local

function printhelp
{
	echo "usage $0 [OPTIONS]"
  echo " --cflags 	- print compiler flags"
	echo " --libs			- print linker flags"
  echo " --prefix   - print the installation prefix"
  echo " --datadir  - print the datadir of verlihub"
	echo " --version	- print verlihub's version"
}

case "x$1" in
"x--cflags") echo -I$prefix/include -I$prefix/include/verlihub -I/usr/include/mysql  -DBIG_JOINS=1 -fPIC -fno-strict-aliasing  -I/usr/include
;;

"x--libs") echo -L/usr/lib -lpcre -Wl,-Bsymbolic-functions -rdynamic -L/usr/lib/mysql -lmysqlclient -ldl -lcrypt -L/usr/lib -lGeoIP  -pthread  -L$prefix/lib -lverlihub
;;
"x--prefix") echo $prefix ;;
"x--datadir") echo ${prefix}/share/verlihub ;;
"x--version") 
	echo -n "verlihub version: 0.9.9a"
	cat $prefix/include/verlihub/curr_date_time.h |sed -e "s/^.*\\\"\\(.*\\)\\\"/ \\1/" 
;;
"x--help") printhelp ;;
esac
