#!/bin/bash

prefix=/usr/local

function printhelp
{
	echo "usage $0 [OPTIONS]"
  echo " --cflags 	- print compiler flags"
	echo " --libs			- print linker flags"
  echo " --prefix   - print the installation prefix"
  echo " --datadir  - print the datadir of verlihub"
	echo " --version	- print verlihub's version"
}

case "x$1" in
"x--cflags") echo -I$prefix/include -I$prefix/include/verlihub -I/usr/include/mysql -DPIC -DHAVE_ERRNO_AS_DEFINE=1  -I/usr/include
;;

"x--libs") echo -L/usr/lib64 -lpcre -Wl,-O1 -rdynamic -L/usr/lib64/mysql -lmysqlclient -lz -lcrypt -lnsl -lm -L/usr/lib64 -lssl -lcrypto -lc -lcrypt -L/usr/lib -lGeoIP  -pthread -L$prefix/lib -lverlihub
;;
"x--prefix") echo $prefix ;;
"x--datadir") echo ${prefix}/share/verlihub ;;
"x--version") 
	echo -n "verlihub version: 0.9.8d-RC2"
	cat $prefix/include/verlihub/curr_date_time.h |sed -e "s/^.*\\\"\\(.*\\)\\\"/ \\1/" 
;;
"x--help") printhelp ;;
esac
