INSERT IGNORE INTO file_trigger (command,send_as,def,descr,min_class,flags) VALUES
	('+motd','MOTD','%[CFG]/motd','Message of the day',0,4),
	('+motd_reg','MOTD','%[CFG]/motd_reg','Message of the day',1,4),
	('+motd_vip','MOTD','%[CFG]/motd_vip','Message of the day',2,4),
	('+motd_op','MOTD','%[CFG]/motd_op','Message of the day',3,4),
	('+motd_cheef','MOTD','%[CFG]/motd_cheef','Message of the day',4,4),
	('+motd_admin','MOTD','%[CFG]/motd_admin','Message of the day',5,4),
	('+motd_master','MOTD','%[CFG]/motd_master','Message of the day',10,4),
	('+help_usr','HELP','%[CFG]/help_usr','Help text',0,8),
	('+help_reg','HELP','%[CFG]/help_reg','Help text',1,8),
	('+help_vip','HELP','%[CFG]/help_vip','Help text',2,8),
	('+help_op','HELP','%[CFG]/help_op','Help text',3,8),
	('+help_cheef','HELP','%[CFG]/help_cheef','Help text',4,8),
	('+help_admin','HELP','%[CFG]/help_admin','Help text',5,8),
	('+help_master','HELP','%[CFG]/help_master','Help text',10,8),
	('+rules','RULES','%[CFG]/rules','Hub rules',0,2),
	('+faq','FAQ','%[CFG]/faq','Frequently asked quenstions',0,2),
	('+sysversion','SystemVersion','/proc/version','Operating System Version',11,4)